version: '2'
services:
  dokify-app:
    image: rafaelcalleja/dokify-challenge:latest
    hostname: dokify-app
    domainname: int
    tty: true
    stdin_open: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9000:9000"
    links:
      - "db:db"
  db:
    image: mysql:latest
    volumes:
      - "dokify-app-mysql-2:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - dokify-app
    volumes_from:
      - dokify-app
    ports:
      - "8443:443"
      - "8080:80"
volumes:
  dokify-app-mysql-2:
