AppBundle\Entity\Agreement:
    type: entity
    table: Agreement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
