AppBundle\Entity\CompanyHasAgreement:
    type: entity
    table: company_has_agreement
    indexes:
        fk_Agreement_has_Company_Company1_idx:
            columns:
                - company_id
        fk_agree_has_buyer:
            columns:
                - buyer
        fk_agree_has_payer:
            columns:
                - payer
        IDX_73E2EA1624890B2B:
            columns:
                - agreement
    id:
        companyId:
            associationKey: true
        buyer:
            associationKey: true
        payer:
            associationKey: true
        agreement:
            associationKey: true
    manyToOne:
        agreement:
            targetEntity: Agreement
            cascade: ["persist"]
            onDelete: CASCADE
            joinColumn:
              name: agreement
              onDelete: CASCADE
              referencedColumnName: id
        companyId:
            targetEntity: Company
            cascade: ["persist"]
            onDelete: CASCADE
            joinColumn:
              name: company_id
              onDelete: CASCADE
              referencedColumnName: id
        payer:
            targetEntity: Company
            cascade: ["persist"]
            onDelete: CASCADE
            joinColumn:
              name: payer
              onDelete: CASCADE
              referencedColumnName: id
        buyer:
            targetEntity: Company
            cascade: ["persist"]
            onDelete: CASCADE
            joinColumn:
              name: buyer
              onDelete: CASCADE
              referencedColumnName: id
    lifecycleCallbacks: {  }
